apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: java-app-hpa
   namespace: java-app
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: java-app
   minReplicas: 2
   maxReplicas: 10
   metrics:
      - type: Resource
        resource:
           name: cpu
           target:
              type: Utilization
              averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
   name: java-app-pdb
   namespace: java-app
spec:
   minAvailable: 1
   selector:
      matchLabels:
         app: java-app
