version: "3"

services:
   mysql:
      image: mysql:latest
      container_name: mysql-db
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
         MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
         MYSQL_USER: ${MYSQL_USER:-admin}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      ports:
         - "3306:3306"
      volumes:
         - mysql-data:/var/lib/mysql
   java_app:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: java-app
      restart: always
      ports:
         - "8080:8080"
      depends_on:
         - mysql

volumes:
   mysql-data:
