apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: java-app-replicaset
spec:
   replicas: 2
   selector:
      matchLabels:
         app: java-app
   template:
      metadata:
         labels:
            app: java-app
      spec:
         containers:
            - env:
                 - name: SPRING_DATASOURCE_PASSWORD
                   value: admin
                 - name: SPRING_DATASOURCE_URL
                   value: jdbc:mysql://mysql:3306/db
                 - name: SPRING_DATASOURCE_USERNAME
                   value: admin
              image: filipeborba/fast-food-app:v4
              name: java-app
              ports:
                 - containerPort: 8080
                   protocol: TCP
              resources:
                 requests:
                    memory: "64Mi"
                    cpu: "250m"
                 limits:
                    memory: "128Mi"
                    cpu: "500m"
         restartPolicy: Always
