apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: java-app-hpa
   namespace: java-app
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: java-app
   minReplicas: 2
   maxReplicas: 10
   metrics:
      - type: Resource
        resource:
           name: cpu
           target:
              type: Utilization
              averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
   name: java-app-pdb
   namespace: java-app
spec:
   minAvailable: 1
   selector:
      matchLabels:
         app: java-app
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: java-app-replicaset
   namespace: java-app
spec:
   replicas: 2
   selector:
      matchLabels:
         app: java-app
   template:
      metadata:
         labels:
            app: java-app
      spec:
         restartPolicy: Always
         containers:
            - name: java-app
              image: filipeborba/fast-food-app:v4
              env:
                 - name: SPRING_DATASOURCE_PASSWORD
                   value: admin
                 - name: SPRING_DATASOURCE_URL
                   value: jdbc:mysql://mysql.mysql-data.svc.cluster.local:3306/db
                 - name: SPRING_DATASOURCE_USERNAME
                   value: admin
              ports:
                 - containerPort: 8080
                   protocol: TCP
              resources:
                 requests:
                    memory: "128Mi"
                    cpu: "250m"
                 limits:
                    memory: "256Mi"
                    cpu: "500m"
