apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      kompose.cmd: kompose convert
      kompose.version: 1.34.0 (HEAD)
   labels:
      io.kompose.service: java-app
   name: java-app
spec:
   replicas: 1
   selector:
      matchLabels:
         io.kompose.service: java-app
   template:
      metadata:
         annotations:
            kompose.cmd: kompose convert
            kompose.version: 1.34.0 (HEAD)
         labels:
            io.kompose.service: java-app
      spec:
         containers:
            - env: 
                 - name: SPRING_DATASOURCE_PASSWORD
                   value: admin
                 - name: SPRING_DATASOURCE_URL
                   value: jdbc:mysql://mysql:3306/db
                 - name: SPRING_DATASOURCE_USERNAME
                   value: admin
              image: filipeborba/fast-food-app:v4
              name: java-app
              ports:
                 - containerPort: 8080
                   protocol: TCP
         restartPolicy: Always
