apiVersion: v1
kind: Service
metadata:
   name: java-app
   labels:
      app: java-app
spec:
   ports:
      - name: http
        port: 8080
        targetPort: 8080
   selector:
      app: java-app
