apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-data
   labels:
      app: mysql
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
   storageClassName: manual
