apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-data
spec:
   capacity:
      storage: 1Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: manual
   hostPath:
      path: "/mnt/data"
